#!/usr/bin/env python3

import argparse
import rethinkdb

parser = argparse.ArgumentParser(description="Clear a tweet table.")
parser.add_argument("--password")
parser.add_argument("--database", required=True)
parser.add_argument("--table", default="tweets")
flags = parser.parse_args()

rethinkdb.connect(password=flags.password).repl()
rethinkdb.db(flags.database).table(flags.table).delete().run()
