#!/usr/bin/env python3

import argparse
import rethinkdb

parser = argparse.ArgumentParser(description="Count rows in a tweet table.")
parser.add_argument("--database", required=True)
parser.add_argument("--table", default="tweets")
flags = parser.parse_args()

rethinkdb.connect().repl()
print(rethinkdb.db(flags.database).table(flags.table).count().run())
